# Generated by Django 4.2.10 on 2025-04-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='size',
        ),
    ]
