# Generated by Django 4.2.10 on 2025-04-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_options_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='size',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='description',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
