# Generated by Django 4.2.10 on 2025-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clothing_delete_clothingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='image_path',
        ),
        migrations.AddField(
            model_name='clothing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
