# Generated by Django 4.2.10 on 2025-04-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_clothing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='image_keypoints',
            field=models.ImageField(blank=True, null=True, upload_to='keypoints/'),
        ),
    ]
