# Generated by Django 4.2.10 on 2025-04-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_clothing_image_keypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='image_keypoints',
        ),
        migrations.AddField(
            model_name='clothing',
            name='keypoint_value',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
