# Generated by Django 4.2.10 on 2025-04-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_clothing_category_alter_clothing_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='keypoint_value',
        ),
        migrations.AddField(
            model_name='clothing',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
